### ISSUE TITLE
Cannot return tuple type

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/impala#12]
The following code crashes :

``` rust
type Blob = (i32, i32);
fn blobify(i: i32) -> Blob {
    (i, i)
}

fn main() -> () {
    let b = blobify(42);
}
```

Run with _-emit-thorin_.

**Comment by leissa** [comment]
Can you plz commit an appropriate test in ```impala/test/codegen```?
Thx.

**Comment by madmann91** [comment]
See commit 95b2587fefbf96495046afc8406df9bebac004b4.

**Comment by leissa** [comment]
* for codegen tests we either need to return ```true``` to pass them or we need to submit an appropriate output file the test suite can compare
* also, simply mention the issue number in the commit message; the commit will be automatically updated in the issue

**Comment by leissa** [comment]
The bug hast to do with this weird thing that
```fn(A) -> (B, C)```
is
```fn(A, fn(B, C))```
and not
```fn(A, fn((B, C))```.
This is already dealt with in ther parser when parsing the ```-> (```. So with the typedef above. The type would be:
```fn(A, fn((B, C))```.
But at some point, it gets mixed up. The correct fix would be to have in the type system that
```T == (T)```
but this is not going to happen any time soon. I'll try to find a workaround.

**Comment by leissa** [comment]
this one is really nasty. Would it be ok for you to postpone a fix for this bug?

**Comment by leissa** [comment]
Oh, forgot to mention that withouth the typedef the code works. As I mentioned: The reason is that ```fn() -> (...)``` is parsed in a special way.

**Comment by madmann91** [comment]
Fixed in master.
