### ISSUE TITLE
Partial Evaluation is being performed unexpectedly

### ISSUE THREAD

**Issue by tonywmnix** [AnyDSL/impala#2]
Hi,
For the unroll.impala test, if I add a version of range() after a call to @ range it is still doing partial evaluation. Is this expected?
```rust
let unroll = 10;
for i in @range(0, unroll) {
    arr(0) = foo(i);
}
for i in range(0, unroll) { // Is being evaluated
    arr(0) = foo(i);
}
```

**Comment by leissa** [comment]
no, this is a bug. However, it should be fixed in the current new_master branch. However, this branch still has some other issues. So we haven't merged back yet.

**Comment by leissa** [comment]
fixed in new_master
