### ISSUE TITLE
Bitwise negation needed

### ISSUE THREAD

**Issue by madmann91** [AnyDSL/impala#4]
There is currently no negation operator in impala. It should be included since it is useful for masks and bit-wise arithmetic (bit shifts are already implemented). The negation sign in C is the tilde ~. We cannot use it here because it is used by owned pointers. What symbol should we use ?

**Comment by leissa** [comment]
we use the same as in rust:
* ```!int_expr``` is negate
* ```!bool_expr``` is logical not.

**Comment by madmann91** [comment]
OK. But then what about logical not on integers ? Do we have to do :

    fn not(i: i32) -> i32 {
        if i == 0 { 0 } else { 1 }
    }

**Comment by leissa** [comment]
yes. The philosophie behind impala is to not have implicit casts. Usually, if you have this in C:
```C
if (!i) {...}
```
you would do this in Impala
```
if i == 0 {...}
```

**Comment by leissa** [comment]
one final remark: if you really want to have sth like your suggested ```not``` function (which I don't find useful anyway) you may want to do sth like this:
```rust
!(i as bool) as int
```
