### ISSUE TITLE
How to convert a double address to a double array adress?

### ISSUE THREAD

**Issue by PupoSDC** [AnyDSL/impala#66]
**Short Version**

Is there any way to convert a reference of type double to a reference of 
an array of doubles?

```rust
&mut double -> &mut [double]
```

**Long Version**

I have a function with the following (simplified) signature:

```rust
fn demo( input: &mut [double] ) -> () {
    // Irrelevant to the topic
}
```
I'd like to be able to call this method passing a reference to a cell in an array
which may not be 0. For example, in this minimalist example i want to call
the demo function for the array at entry 3.

```rust
fn main( array: &mut [double] ){
   demo( &mut array(3), 2  )
}
```

The above code throws the following error:

```sh
error: mismatched types: expected '&mut <infer error: [f64], f64>' but found '&mut f64' as argument type
```

Please ignore all the memory and segfault risks of this demo code. They were 
considered in the full version of the code. Also, I'd like to avoid an approach
where a reference to the array and an integer for the entry are passed to the
demo function. Eg.:

```rust
fn demo( input: &mut [double], entry: uint ) -> () {
    // Not what i'm looking for.
}

fn main( array: &mut [double] ){
   demo( array, 3  )
}
```
Thank you for your help

**Comment by madmann91** [comment]
In your code snippet, the type of:
```rust
&mut array(3)
```

is `&mut double`. You then try to pass this to `demo`, which takes a `&mut [double]` as argument. The error message simply state that the two types are incompatible (it tries to unify `&mut double` and `&mut [double]` and returns `&mut <infer error: [double], double>`).

What you want to do is to take cast your pointer of type `&mut double` to `&mut [double]`. This can be achieved using `bitcast`, or the `as` operator:

 fn demo( input: &mut [double], entry: uint ) -> () {
    // ...
}

fn main( array: &mut [double] ){
   demo( &mut array(3) as &mut [double], 3  )
   // or: demo(bitcast[&mut [double]](&mut array(3)), 3)
}

**Comment by PupoSDC** [comment]
That worked wonderfully.

Thank you for your help!
