### ISSUE TITLE
SimdType is an ArrayType

### ISSUE THREAD

**Issue by leissa** [AnyDSL/impala#8]
This has the implication that we can implicitly cast ```[4 x int]``` to ```simd[4 x int]```.
We could either change the subclass relation in the C++ implementation or fix is_subtype.

**Comment by madmann91** [comment]
I see that it can create problems in the code generation part, but it is also nice to be able to convert between simd and non-simd types. If we really need to remove it, then I would go for changing the class hierarchy. That makes more sense, I believe.

**Comment by leissa** [comment]
you could still use an explicit cast for that:
```rust
let a: [4 x int] = simd[1, 2, 3, 4] as [4 x int]
```
however, code generation will break at the moment.

**Comment by leissa** [comment]
see also my pull request.
