### ISSUE TITLE
How to read user input?

### ISSUE THREAD

**Issue by enty8080** [AnyDSL/impala#87]
How to read user input in impala? Like in cpp:

```cpp
#include <iostream>
using namespace std;

int main() {
    int a; cin >> a;
}
```

**Comment by richardmembarth** [comment]
The focus of AnyDSL is mainly on writhing high-performance libraries. For input/output, we rely typically on C/C++.
See https://anydsl.github.io/Tutorial.html for how this can be done.

**Comment by madmann91** [comment]
Alternatively, you can import C functions, like `fgets`:

```rust
struct FILE {}
extern "C" {
    fn "stdin_" stdin() -> &FILE;
    fn fgets(&mut [u8], i32, &FILE) -> &[u8];
}

fn main() -> i32 {
    let mut str : [u8 * 256];
    fgets(&mut str, 256, stdin());
    0
}
```

You'll need to compile and link with the C standard library and the additional C file containing a definition for ```stdin```:

```c
#include <stdio.h>
void* stdin_(void) { return stdin; }
```

Note that this _will not_ work if you compile the above file as a C++ file as the name of the function will be mangled (use ```gcc```, not ```g++```).
